language: node_js
node_js: 12

env:
  global:
    - PACK_NAME=adisakshya-extension-pack
    - VERSION=$(node assets/version.js -p)

jobs:
  include:
    - stage: build
      name: "Build and Test"
      install:
        # Install VSCE
        - npm install --global vsce
      script:
        # Pack extensions
        - npm run pack
      workspaces:
        create:
          name: ws1
          paths:
            - /home/travis/build/adisakshya/extension-pack/${PACK_NAME}-${VERSION}.vsix
    - stage: GitHub Release
      name: "Publish VSIX file on GitHub Release"
      workspaces:
        use: ws1
      install: skip
      script: skip
      deploy:
        provider: releases
        api_key: ${GITHUB_SECURE_TOKEN}
        name: ${VERSION}
        file: /home/travis/build/adisakshya/extension-pack/${PACK_NAME}-${VERSION}.vsix
        skip_cleanup: true
        on:
          tags: true

notifications:
  email: false
